<a href="https://colab.research.google.com/github/roser740/Data-Analytics/blob/main/TASQUES%20S8/TS8_01_roser_carrera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tasca S8.01. Analítica de dades en Pandas**

En aquest sprint treballaràs un procés complet d'**Exploratory Data Analysis** (EDA) utilitzant Python i Pandas, simulant una situació real d'anàlisi de dades dins d'una empresa.

L'objectiu no és només obtenir resultats, sinó entendre el dataset, detectar problemes, prendre decisions analítiques i justificar-les, seguint una metodologia estructurada similar a la que utilitzaria un/a analista de dades en un entorn professional.

El sprint està organitzat en tres nivells de dificultat, on cada nivell aprofundeix més en:

*   Qualitat de les dades.
*   Capacitat de diagnòstic.
*   Tractament d'errors.
*   Enriquiment del dataset.

Procura que el teu codi sigui clar i organitzat.

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [25]:
import pandas as pd

# **Nivell 1 - EDA estructurat i neteja bàsica**

Tenim un dataset d'empleats obtingut a partir d'una enquesta interna. Abans de poder extreure conclusions, cal assegurar-nos que les dades són correctes, consistents i analitzables.

# **Exercici 1: Exploració inicial del dataset**

🎯 **Objectiu:** entendre l’estructura general del dataset i detectar possibles problemes abans de començar a netejar o transformar dades.

En aquest exercici has de realitzar una exploració inicial del DataFrame per respondre, com a mínim, a les següents preguntes:
*   Quantes files i columnes té el dataset?
*   Quin tipus de dades conté cada columna?
*   Hi ha files duplicades?
*   Les dades semblen coherents a primera vista?
*   Detectes possibles problemes o inconsistències evidents?

Per fer-ho, hauràs de:
*   Analitzar les dimensions del dataset
*   Mostrar una mostra representativa de files
*   Revisar els tipus de variables
*   Detectar files duplicades
*   Les dades semblen coherents a primera vista?
*   Identificar i descriure possibles problemes inicials (sense solucionar-los encara)

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Obrir el fitxer i carregar dades en un dataframe.
2. Obtenir les dimensions del dataframe.
3. Mostrar 10 files del dataframe.
4. Mostrar el tipus de dades de cada columna.
5. Detectar files duplicades
6. Detectar DNI's duplicats.
7. Detectar camps nuls.
8. Detectar valors incorrectes o incoherents en els diferents camps:
    *   Problemes de codificació i accentuació
    *   Data de naixement
    *   Gènere
    *   Salari mensual
    *   Fills
    *   Grup Professional
    *   Cotxe
    *   Temperatura

## 🧩 **Implementació**

In [2]:
def ordenar_dataframe(df, camp, ordre):
#Modifica el dataframe ordenant-lo pel camp indicat i seguint l'ordre indicat (True: ascendent, False: descendent)

    df.sort_values(by=camp, ascending=ordre, inplace=True)

In [3]:
def mostrar_dataframe(df, títol):
#Presenta les dades en format tabular amb el títol indicat

    # Mostrem títol
    print("\n" + "="*100)
    print(títol)
    print("="*100)
    # La funció display mostra les dades del dataframe en format taula.
    # Utilitzem la propietat style per amagar la columna de l'índex.
    display(df.style.hide(axis='index'))

### 1. Càrrega de les dades

In [26]:

url = "https://github.com/roser740/Data-Analytics/raw/main/TASQUES%20S8/sprint8_complex.xlsx"
df = pd.read_excel(url, header=3, index_col=0)
# header: fila on trobem el nom de les columnes
# index_col: columna on trobem l'índex

### 2. Obtenir les dimensions del dataframe

In [27]:
print ("Número de files: ", df.shape[0])
print ("Número de columnes: ", df.shape[1])

Número de files:  1007
Número de columnes:  19

### 3. Mostra de les dades del dataframe

In [28]:
print(df.head(10).to_string(index=False))

   Nom           Cognoms       DNI País d'origen                     Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual Fills No Fills Grup Professional               CÃ rrec  Nombre_fills Te_cotxe  Km_anuals  Consum_mitja_L_100km  Temperatura_mitjana_ciutat
 Joana       Gil Navarro 66722344X       Espanya                 Valladolid              23.0               3.0            1958.0   Dona      1,469 â‚¬  True      NaN            Grup B       Cap de projecte           3.0     True    32108.0                  25.0                        10.1
  Marc            MuÃ±oz 48840994W       Espanya                    Alacant               8.0              11.0            1960.0      H      2,718 â‚¬   NaN     True            Grup C        Senior analyst           0.0     True    19496.0                  10.4                        18.7
   Noa             Serra 14308421X       Espanya                    Alacant              27.0               4.0            1961.0      D     1358 euros  True      NaN            Grup A            TÃ¨cnic IT           4.0      NaN        NaN                   NaN                        16.7
   Pol               Gil 58586340F       Espanya                    Sevilla              13.0              10.0            1985.0      H      1,478 â‚¬  True      NaN            Grup B          Data Analyst           2.0    False        NaN                   NaN                        18.3
 David              Vila 82070937P       Espanya                     Bilbao              29.0              11.0            1965.0   Dona      1,284 â‚¬   NaN     True            Grup B         Administratiu           NaN     True        NaN                  11.8                        13.1
Alexia              Puig 25014631B       Espanya Las Palmas de Gran Canaria               1.0               8.0            1978.0      D      2,069 â‚¬   NaN     True            Grup B       Cap de projecte           0.0      NaN        NaN                   NaN                        19.9
 David       GÃ³mez Vila 36998038E       Espanya                      Palma              25.0               9.0            1971.0      D      2,349 â‚¬   NaN     True            Grup B       Cap de projecte           NaN     True     6196.0                  10.6                        17.8
Carmen            LÃ³pez 47376585K       Espanya                  Barcelona               8.0               9.0            1962.0      H      2,855 â‚¬  True      NaN            Grup C Responsable de vendes           4.0     True    20000.0                   5.9                        15.4
  Nora Andersen Pedersen 37289414J       Noruega                  Stavanger               8.0               3.0            1963.0      D      1,338 â‚¬   NaN     True            Grup B       Analista junior           0.0    False        NaN                   NaN                         7.6
  Alba           GarcÃ­a 75181648S       Espanya Las Palmas de Gran Canaria              32.0               0.0            1940.0      H      1,450 â‚¬  True      NaN            Grup A        Senior analyst           4.0    False        NaN                   NaN                        20.1

### 4. Tipus de dades

In [29]:
print(df.dtypes)

Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

### 5. Files duplicades

In [40]:
files_duplicades = df.duplicated(keep = False)
print("Número de files duplicades: ", files_duplicades.sum())
print("Files duplicades")
print(df[files_duplicades].sort_values(by='DNI').to_string())

Número de files duplicades:  8
Files duplicades
          Nom          Cognoms        DNI País d'origen     Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual Fills No Fills Grup Professional                CÃ rrec  Nombre_fills Te_cotxe  Km_anuals  Consum_mitja_L_100km  Temperatura_mitjana_ciutat
757     Oriol           Ferrer  52590001R       Espanya   Zaragoza              15.0               7.0            1973.0      D         786â‚¬   NaN     True            Grup A               Analista           0.0     True    81381.0                   6.5                        13.9
1004    Oriol           Ferrer  52590001R       Espanya   Zaragoza              15.0               7.0            1973.0      D         786â‚¬   NaN     True            Grup A               Analista           0.0     True    81381.0                   6.5                        13.9
464       Ida  Karlsen Eriksen  55283701C       Noruega       Oslo               2.0               9.0            1992.0      D      1,614 â‚¬  True      NaN            Grup B               Analista           3.0      NaN        NaN                   NaN                        10.6
1001      Ida  Karlsen Eriksen  55283701C       Noruega       Oslo               2.0               9.0            1992.0      D      1,614 â‚¬  True      NaN            Grup B               Analista           3.0      NaN        NaN                   NaN                        10.6
730   Claudia       Gil Ferrer  55297384F       Espanya  ValÃ¨ncia               1.0              11.0            1981.0      H      1.789 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0     True    29952.0                   9.2                        20.3
1003  Claudia       Gil Ferrer  55297384F       Espanya  ValÃ¨ncia               1.0              11.0            1981.0      H      1.789 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0     True    29952.0                   9.2                        20.3
372      Alba           MuÃ±oz  97954019T       Espanya     Bilbao              25.0              10.0            1983.0      D      1,409 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0      NaN        NaN                   NaN                        14.7
1002     Alba           MuÃ±oz  97954019T       Espanya     Bilbao              25.0              10.0            1983.0      D      1,409 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0      NaN        NaN                   NaN                        14.7

### 6. DNI's duplicats

In [31]:
dni_duplicats = df.duplicated(subset=['DNI'], keep= False)
print("Número de DNI's duplicats: ", dni_duplicats.sum())
print("DNI's duplicats")
print(df[dni_duplicats].sort_values(by='DNI').to_string())

Número de DNI's duplicats:  24
DNI's duplicats
          Nom          Cognoms        DNI País d'origen     Ciutat  Dia de Naixement  Mes de Naixement  Any de Naixement Gènere Salari mensual Fills No Fills Grup Professional                CÃ rrec  Nombre_fills Te_cotxe  Km_anuals  Consum_mitja_L_100km  Temperatura_mitjana_ciutat
604      Laia          Navarro  15909601K       Espanya     Bilbao              30.0               5.0            1958.0      D      1,676 â‚¬  True    False            Grup A               Analista           1.0     True       50.0                   NaN                        14.2
250      Laia     Navarro Vila  15909601K       Espanya     Bilbao              30.0               5.0            1958.0      D     1235 euros  True     True            Grup D        Analista junior           0.0    False        NaN                   NaN                        10.3
759     Oriol           GÃ³mez  16618423V       Espanya    Sevilla              10.0               1.0            1968.0    NaN      2,000 â‚¬   NaN      NaN            Grup A  Responsable de vendes           5.0      NaN        NaN                   NaN                        20.7
758     Oriol           GÃ³mez  16618423V       Espanya    MÃ laga              10.0               1.0            1968.0      H     1879 euros  True      NaN            Grup B           Data Analyst           4.0    False        NaN                   NaN                         NaN
754     Oriol           GÃ³mez  16618423V       Espanya  Barcelona              10.0               1.0            1968.0   Home      2.358 â‚¬  True      NaN               NaN                    NaN           4.0      NaN        NaN                   NaN                         NaN
654     Oriol           GÃ³mez  16618423V       Espanya     Madrid              10.0               1.0            1968.0   Home     1731 euros  True      NaN            Grup B           Data analyst           4.0      NaN        NaN                   NaN                         NaN
692    Alexia     PÃ©rez DÃ­az  49529438G       Espanya    MÃ laga              12.0              10.0            1981.0   Dona        1663â‚¬   NaN     True            Grup C        Cap de projecte           NaN     True    80000.0                  10.7                        16.9
558    Alexia     PÃ©rez DÃ­az  49529438G       Espanya    MÃ laga              12.0              10.0            1981.0   Dona      1,176 â‚¬   NaN     True            Grup A           Data Analyst           0.0    False        NaN                   NaN                        38.0
757     Oriol           Ferrer  52590001R       Espanya   Zaragoza              15.0               7.0            1973.0      D         786â‚¬   NaN     True            Grup A               Analista           0.0     True    81381.0                   6.5                        13.9
1004    Oriol           Ferrer  52590001R       Espanya   Zaragoza              15.0               7.0            1973.0      D         786â‚¬   NaN     True            Grup A               Analista           0.0     True    81381.0                   6.5                        13.9
142     Marta             Ruiz  54013571W       Espanya      Palma              24.0               5.0            1982.0      H      1,276 â‚¬  True     True            Grup A               Analista           0.0    False        NaN                   NaN                        15.7
89    Guillem      Pujol Costa  54013571W       Espanya  A CoruÃ±a              17.0               7.0            1983.0      D      1.574 â‚¬  True      NaN            Grup B           Project lead           4.0    False        NaN                   NaN                        14.6
1001      Ida  Karlsen Eriksen  55283701C       Noruega       Oslo               2.0               9.0            1992.0      D      1,614 â‚¬  True      NaN            Grup B               Analista           3.0      NaN        NaN                   NaN                        10.6
464       Ida  Karlsen Eriksen  55283701C       Noruega       Oslo               2.0               9.0            1992.0      D      1,614 â‚¬  True      NaN            Grup B               Analista           3.0      NaN        NaN                   NaN                        10.6
1003  Claudia       Gil Ferrer  55297384F       Espanya  ValÃ¨ncia               1.0              11.0            1981.0      H      1.789 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0     True    29952.0                   9.2                        20.3
730   Claudia       Gil Ferrer  55297384F       Espanya  ValÃ¨ncia               1.0              11.0            1981.0      H      1.789 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0     True    29952.0                   9.2                        20.3
281    Xavier            Vidal  90585882A       Espanya    Alacant               2.0               7.0            1958.0      H     1179 euros   NaN      NaN            Grup A             TÃ¨cnic IT           0.0     True    63574.0                   6.0                        16.8
114       Pol            Serra  90585882A       Espanya     Girona               4.0              12.0            1960.0      H      1,178 â‚¬   NaN     True            Grup A           Data Analyst           NaN    False        NaN                   NaN                        16.2
104     Oriol      Vila Casals  90585882A       Espanya     Madrid              30.0               9.0            1964.0      H     1987 euros   NaN     True            Grup B  Responsable de vendes           0.0    False        NaN                   NaN                        13.5
913      Sara            Serra  90585882A       Espanya  Tarragona              28.0               5.0            2002.0   Dona      1,000 â‚¬   NaN     True            Grup A          Administratiu           0.0    False        NaN                   NaN                        15.8
1000     Sara            Serra  90585882A       Espanya  Tarragona              28.0               5.0            2002.0      D      1,073 â‚¬   NaN     True            Grup A          Administratiu           0.0    False        NaN                   NaN                        15.8
25       Sara            Serra  90585882A       Espanya  Tarragona              28.0               5.0            2002.0      D        993 â‚¬   NaN     True            Grup A          Administratiu           0.0    False        NaN                   NaN                        15.8
1002     Alba           MuÃ±oz  97954019T       Espanya     Bilbao              25.0              10.0            1983.0      D      1,409 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0      NaN        NaN                   NaN                        14.7
372      Alba           MuÃ±oz  97954019T       Espanya     Bilbao              25.0              10.0            1983.0      D      1,409 â‚¬   NaN     True            Grup B  Responsable de vendes           0.0      NaN        NaN                   NaN                        14.7

### 7. Valors nuls

Observem

In [10]:
print("Valors nuls" )
print(df.isna().sum())

Valors nuls
Nom                             1
Cognoms                         1
DNI                             1
País d'origen                   1
Ciutat                          1
Dia de Naixement                1
Mes de Naixement                1
Any de Naixement                1
Gènere                         41
Salari mensual                  1
Fills                         588
No Fills                      422
Grup Professional               2
CÃ rrec                         2
Nombre_fills                  298
Te_cotxe                      349
Km_anuals                     692
Consum_mitja_L_100km          746
Temperatura_mitjana_ciutat     71
dtype: int64

### 8. Detecció de dades incorrectes o incoherents

#### a. Problemes de codificació i accentuació

Observem alguns problemes de codificació i accentuació en el nom de les columnes (CÃ rrec ) i també en els camps que contenen text:
*   Nom: ChloÃ©, AdriÃ ...
*   Cognoms: MuÃ±oz, GÃ³mez ...
*   País d'origen: FranÃ§a, ItÃlia ...
*   Ciutat: MÃ laga, ValÃ¨ncia ...
*   Càrrec: TÃ¨cnic IT ...

#### b. Data de naixement

In [33]:
condicio = (df['Dia de Naixement']<1) | (df['Dia de Naixement']>31) | (df['Mes de Naixement']<1) | (df['Mes de Naixement']>12) | (df['Any de Naixement']<1950) | (df['Any de Naixement']>2009)
df.loc[condicio, :]

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
39,Guillem,Vila,92874006W,Espanya,Murcia,0.0,99.0,3000.0,H,dos mil,NaN,True,Grup A,Senior analyst,0.0,NaN,NaN,NaN,NaN
41,Paul,Richard Laurent,43567615Z,FranÃ§a,Bordeaux,32.0,99.0,2019.0,Dona,"1,967 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,False,NaN,NaN,15.2
47,Aina,FernÃ¡ndez,38468360C,Espanya,Zaragoza,-5.0,0.0,3000.0,Home,1939 euros,True,NaN,Grup C,Analista,1.0,True,78064.0,NaN,NaN
53,Aina,Serra,29226889H,Espanya,ValÃ¨ncia,0.0,0.0,2019.0,F,"1,866 â‚¬",NaN,True,Grup B,TÃ¨cnic IT,NaN,False,NaN,NaN,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,David,PÃ©rez,52298598B,Espanya,Murcia,-5.0,0.0,2019.0,Dona,779 â‚¬,NaN,True,Grup A,Analista junior,0.0,NaN,NaN,NaN,19.0
63,Ida,Johansen Kristiansen,41407343V,Noruega,Bergen,32.0,99.0,2019.0,D,"2,759 â‚¬",NaN,True,Grup C,Senior analyst,NaN,False,NaN,NaN,9.1
981,Giulia,Romano,34747698K,ItÃ lia,Torino,32.0,0.0,2026.0,D,"1,316 â‚¬",NaN,True,Grup B,TÃ¨cnic IT,NaN,True,20000.0,9.1,38.0
996,LucÃ­a,Roca Vila,21702378D,Espanya,Alacant,32.0,0.0,1940.0,NaN,1158â‚¬,NaN,True,Grup A,Data Analyst,NaN,NaN,NaN,NaN,19.4
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

#### c. Gènere

In [13]:
df.groupby(['Gènere'],dropna=False)['DNI'].count()

Gènere
??        1
A        24
D       325
Dona    120
F       107
H       280
Home     52
M        34
NC       23
NaN      40
Name: DNI, dtype: int64

#### Salari_mensual

In [37]:
df.groupby(['Salari mensual'])['DNI'].count()

Salari mensual
1,000 â‚¬          1
1,001 â‚¬          1
1,002 â‚¬          1
1,003 â‚¬          2
1,005 â‚¬          1
                  ..
dos mil            7
mil vuit-cents     9
molts              1
n/d               14
tres mil           6
Name: DNI, Length: 855, dtype: int64

#### Fills, No Fills, Nombre_fills

In [14]:
df.groupby(['Nombre_fills','Fills','No Fills'],dropna=False)['DNI'].count()

Nombre_fills  Fills  No Fills
0.0           True   True         34
              NaN    NaN          15
                     True        263
1.0           True   NaN         160
                     False         1
                     True          6
              NaN    NaN           2
                     True          2
2.0           True   NaN          73
                     True          1
              NaN    NaN           1
                     True          4
3.0           True   NaN          60
                     True          3
              NaN    NaN           1
                     True          1
4.0           True   NaN          77
                     True          1
              NaN    NaN           1
                     True          2
5.0           NaN    NaN           1
NaN           True   True          3
              NaN    NaN          30
                     True        264
Name: DNI, dtype: int64

#### Grup Professional

In [16]:
df.groupby(['Grup Professional'],dropna=False)['DNI'].count()

Grup Professional
Grup A    466
Grup B    357
Grup C    140
Grup D     41
Z           1
NaN         1
Name: DNI, dtype: int64

#### Te_cotxe, km_anuals, Consum_mitja

In [15]:
df.groupby(['Te_cotxe','Km_anuals','Consum_mitja_L_100km'],dropna=False)['DNI'].count()

Te_cotxe  Km_anuals  Consum_mitja_L_100km
True      -50.0      NaN                       6
           50.0      NaN                       1
           2938.0    0.5                       1
           3920.0    NaN                       1
           3936.0    12.9                      1
                                            ...
           NaN       25.0                      1
                     NaN                      15
NaN        NaN       NaN                     348
False      0.0       NaN                       4
           NaN       NaN                     326
Name: DNI, Length: 240, dtype: int64

# **Exercici 2: Validacions bàsiques de les dades i decisions d'eliminació**

🎯 **Objectiu:** assegurar que les dades compleixen unes condicions mínimes de qualitat i determinar quines files poden continuar sent analitzades i quines s'han de descartar.
En aquest exercici hauràs de validar aspectes clau del dataset que són crítics en qualsevol context real d'anàlisi de dades, prenent decisions justificades sobre la validesa o eliminació de registres.

Aspectes a validar:

» Existeixen identificadors únics (DNI) per a cada persona?

» Què faràs amb les files duplicades o registres repetits?

» Hi ha valors obligatoris que falten o informació incoherent?

» Detectes formats incorrectes, errors de codificació o valors impossibles?

Concretament, hauràs de:

» Corregir possibles problemes de codificació i accentuació en els noms de les columnes i en els valors de text, si escau.

» Detectar i eliminar files duplicades exactes, indicant quants registres s'han eliminat.

» Comprovar la unicitat del DNI. En cas de detectar DNIs duplicats, hauràs d'analitzar la coherència de la informació associada i descartar o anul·lar els registres que no siguin fiables, justificant clarament la decisió presa.

» Identificar els camps clau que no haurien de contenir valors nuls, detectar registres amb informació insuficient i eliminar únicament aquelles files completament buides o amb informació irrecuperable o no substituïble, explicant per què no és possible ni raonable imputar-les.


# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Eliminar files duplicades exactes.
2. Detectar camps clau amb valors nuls.
3. Corregir problemes de codificació i accentuació.
      *   Correcció dels noms de les columnes
      *   Correcció del contingut de les columnes
4. Detectar DNIs duplicats i descartar els erronis.
5. Detectar registres amb informació insuficient.

## 🧩 **Descomponent el problema: naixement de les funcions**

### **1. Eliminar files duplicades**

Hem detectat que hi ha files duplicades és a dir registres que tenen el mateix contingut. En aquest cas

In [17]:
def eliminar_files_duplicades (df):

  print("1.ELIMINACIÓ DE FILES DUPLICADES")
  files_duplicades = df.duplicated(keep = 'last')
  print("    Número de files duplicades: ", files_duplicades.sum())
  print ("    Eliminem files duplicades...")
  df.drop_duplicates(inplace=True)

### **2. Eliminar registres amb DNI nul**

In [18]:
def eliminar_nuls (df):

  print("2. ELIMINACIÓ DE REGISTRES AMB DNI NUL")
  dni_nuls = df.isna()['DNI']
  print("    Número de files amb DNI nul: ", dni_nuls.sum())
  print ("    Eliminem files amb DNI nul...")
  df.dropna(subset = ['DNI'], inplace = True)

### **3. Correcció de problemes de codificació i accentuació**

El problema més comú amb els accents i la codificació és que el text originalment en UTF-8 es llegeix incorrectament com si fos en Latin-1 (ISO-8859-1). Per solucionar-ho, cal "desfer" la lectura incorrecta (codificant de nou a Latin-1) i després "corregir" la lectura (descodificant a UTF-8).

Aquest problema afecta tant els noms de les columnes com els valors de text dins de les columnes. Corregeixo els noms de les columnes i, posteriorment, aplico la mateixa correcció als valors de text de totes les columnes amb tipus dades 'object'.

In [19]:
def descodificar (text):
# Funció que retorna el text que rep com a paràmetre sense errors.

  if isinstance (text, str): # Si el text és un string
    try:
      # Prova de codificar/descodificar string
      return text.encode('latin-1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
      # Si hi ha un error perquè per exemple la cadena ja és correcta
      # retorna el text original
      return text
  # Si el text no és de tipus string no intenta descodificar
  # i retorna text original
  return text

In [20]:
def correccions_codificacio (df):

  print("3. CORRECIÓ PROBLEMES DE CODIFICACIÓ I ACCENTUACIÓ")
  # Correcció dels noms de les columnes
  print ("    Corregim els noms de les columnes...")
  df.columns = [descodificar(col) for col in df.columns]

  # Correcció dels contingut de les columnes
  print ("    Corregim els valors de text de les columnes 'object'...")
  for col in df.columns:
    if df[col].dtype == 'object':
      df[col] = df[col].apply(descodificar)

### **4. Correcció de DNI's duplicats**

El problema més

In [21]:

def correccions_dni_duplicats (df):

  print("4. ELIMINACIÓ DE REGISTRES AMB DNI DUPLICAT")
  dni_duplicats = df.duplicated(subset=['DNI'], keep= False)
  print("    Número de DNI's duplicats: ", dni_duplicats.sum())
  print ("    Eliminem files amb DNI duplicat...")

In [22]:
def mostrar_dataframe(df, títol):
#Presenta les dades en format tabular amb el títol indicat

    # Mostrem títol
    print("\n" + "="*100)
    print(títol)
    print("="*100)
    # La funció display mostra les dades del dataframe en format taula.
    # Utilitzem la propietat style per amagar la columna de l'índex.
    display(df)

## **⭕ Algoritme principal**

In [23]:
def main_validacio(df):
  eliminar_files_duplicades(df)
  eliminar_nuls(df)
  correccions_codificacio (df)
  correccions_dni_duplicats (df)

  #correccions_dni_duplicats(df)
  mostrar_dataframe(df, "DATAFRAME ACTUALITZAT")

In [24]:
main_validacio(df)

1.ELIMINACIÓ DE FILES DUPLICADES
    Número de files duplicades:  4
    Eliminem files duplicades...
2. ELIMINACIÓ DE REGISTRES AMB DNI NUL
    Número de files amb DNI nul:  1
    Eliminem files amb DNI nul...
3. CORRECIÓ PROBLEMES DE CODIFICACIÓ I ACCENTUACIÓ
    Corregim els noms de les columnes...
    Corregim els valors de text de les columnes 'object'...
4. ELIMINACIÓ DE REGISTRES AMB DNI DUPLICAT
    Número de DNI's duplicats:  16
    Eliminem files amb DNI duplicat...

====================================================================================================
DATAFRAME ACTUALITZAT
====================================================================================================

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,Chloé,Dubois,66354268T,França,Nice,2.0,12.0,1958.0,H,"1,954 â‚¬",True,NaN,Grup B,Data Analyst,1.0,NaN,NaN,NaN,11.7
999,Adrià,Vila Díaz,57511543T,Espanya,Palma,31.0,12.0,1991.0,H,"2,010 â‚¬",True,NaN,Grup C,Analista,1.0,False,NaN,NaN,-10.0
1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
651,Kasper,Pettersen,62042563B,Noruega,Oslo,11.0,5.0,1996.0,D,2.290 â‚¬,NaN,True,Grup B,Senior analyst,0.0,True,80000.0,0.5,6.5
1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

# **Exercici 3: Transformacions necessàries i preparació del dataset**

🎯 Objectiu: preparar el dataset perquè sigui coherent, analitzable i estructuralment correcte abans de realitzar qualsevol anàlisi descriptiva.
En aquest exercici hauràs d'aplicar transformacions bàsiques però essencials, orientades a millorar la qualitat de les dades i facilitar l'anàlisi posterior.

Aspectes a revisar i transformar:

» Els valors categòrics estan normalitzats i són consistents?
» Els valors nuls són coherents amb la informació disponible?
» Hi ha redundància de variables que pugui generar problemes analítics?
» Les variables contextuals (com temperatura, salari) estan completes i preparades per a l'anàlisi?
Concretament, hauràs de:

» Normalitzar els valors categòrics per evitar ambigüitats (per exemple, valors que representen el mateix concepte però estan escrits de manera diferent).
» Revisar la coherència dels valors nuls, assegurant que:
Les persones que tenen quilometratge anual i consum mitjà associats disposen de cotxe. En els casos en què consti consum mitjà però no quilometratge anual, caldrà decidir com resoldre aquesta incoherència de manera justificada.
Les persones que tenen un valor en el nombre de fills efectivament tenen fills.
» Unificar la informació sobre fills en una única columna, ja que mantenir diverses columnes amb informació complementària no és òptim i pot generar problemes analítics (redundància o multicolinealitat).
» Validar la temperatura mitjana. En cas que aquesta informació falti, hauràs d'imputar-la utilitzant un criteri raonable (per ciutat o per un nivell superior justificat).
» Revisar i imputar els salaris faltants, aplicant criteris analítics coherents (com ara càrrec, grup professional, ciutat, gènere o franja d'edat).

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Normalitzar el camp Gènere.
2. Normalitzar els camps Te_cotxe, kms_anuals i consum_mitjà.
3. Normalitzar els camps Fills, No Fills, Nombre_fills.
      *   Correcció dels noms de les columnes
      *   Correcció del contingut de les columnes
4. Revisar el camp TemperaturaÇ_mitjana.
5. Revisar el camp Salari_anual.

## 🧩 **Descomponent el problema: naixement de les funcions**

### **1. Normalitzar el camp Gènere**

Hem detectat que hi ha files duplicades és a dir registres que tenen el mateix contingut. En aquest cas

In [ ]:
def assignar_genere (x):
    if (x == 'D') or (x == 'Dona') or (x == 'F'):
        return 'D'
    elif (x == 'H') or (x == 'Home') or (x == 'M'):
        return 'H'
    else
        return 'ND'

# Assignem valor al camp Gènere
df['Gènere'] = df['Gènere'].apply (assignar_genere)

### **1. Normalitzar el camp Te_cotxe...**

Hem detectat que hi ha files duplicades és a dir registres que tenen el mateix contingut. En aquest cas

In [ ]:
# Assignem el valor 0.0 als valors nuls del camp kms_anuals i Consum_mitja_L_100km
df.fillna({'km_anuals':0.0}, inplace = True)
df.fillna({'Consum_mitja_L_100km':0.0}, inplace = True)
# Assignem el valor 0 al camp km_anuals en els registres que tenen  km_anuals negatius
df.loc[df['km_anuals'] < 0.0, 'km_anuals'] = 0.0
# Assignem el valor 9999.0 al camp km_anuals en els registres que tenen consum_mitja informat i km_anuals == 0
df.loc[(df['Consum_mitja_L_100km'] != 0.0) AND (df['km_anuals'] == 0.0), 'km_anuals'] = 9999.0
# Assignem valor al camp Te_cotxe en funció del camp Km_anuals
df.loc[df['km_anuals'] != 0.0, 'Te_cotxe'] = True
df.loc[df['km_anuals'] == 0.0, 'Te_cotxe'] = False

### **3. Normalitzar el camp Fils, No fills, Nombre_fills**

Hem detectat que hi ha files duplicades és a dir registres que tenen el mateix contingut. En aquest cas

In [ ]:
# Assignem el valor 0.0 als valors nuls del camp Nombre_fills
df.fillna({'Nombre_fills':0.0}, inplace = True)
# Assignem valor al camp Fills en funció del camp Nombre_fills
df.loc[df['Nombre_fills'] != 0.0, 'Fills'] = True
df.loc[df['Nombre_fills'] == 0.0, 'Fills'] = False
# Eliminem la columna No Fills
df.drop(columns = ['No fills'], inplace = True)

### **5. Revisar camp Salari_mensual**

Hem detectat que hi ha files duplicades és a dir registres que tenen el mateix contingut. En aquest cas

In [ ]:
df.loc[df['Salari mensual'] == 'dos mil', 'Salari mensual'] = 2000.0
df.loc[df['Salari mensual'] == 'mil vuit-cents', 'Salari mensual'] = 1800.0
df.loc[df['Salari mensual'] == 'tres mil', 'Salari mensual'] = 3000.0

### **5. Revisar camps de la data de naixement**

Hem detectat que hi ha files duplicades és a dir registres que tenen el mateix contingut. En aquest cas

In [ ]:
condicio = (df['Dia de Naixement']<1) | (df['Dia de Naixement']>31) | (df['Mes de Naixement']<1) | (df['Mes de Naixement']>12) | (df['Any de Naixement']<1950) | (df['Any de Naixement']>2009)
df.loc[condicio, :]

# Assignem valors als camps dia, mes i any de naixement incorrectes
df.loc[condicio, 'Dia de Naixement'] = 99.0
df.loc[condicio, 'Mes de Naixement'] = 99.0
df.loc[condicio, 'Any de Naixement'] = 9999.0

## **⭕ Algoritme principal**

In [ ]:
def main_transformacio(df):
  eliminar_files_duplicades(df)

  mostrar_dataframe(df, "DATAFRAME ACTUALITZAT")

In [ ]:
main_transformacio (df)