# **Tasca S8.01. Analítica de dades en Pandas**

En aquest sprint treballaràs un procés complet d'**Exploratory Data Analysis** (EDA) utilitzant Python i Pandas, simulant una situació real d'anàlisi de dades dins d'una empresa.

L'objectiu no és només obtenir resultats, sinó entendre el dataset, detectar problemes, prendre decisions analítiques i justificar-les, seguint una metodologia estructurada similar a la que utilitzaria un/a analista de dades en un entorn professional.

El sprint està organitzat en tres nivells de dificultat, on cada nivell aprofundeix més en:

*   Qualitat de les dades.
*   Capacitat de diagnòstic.
*   Tractament d'errors.
*   Enriquiment del dataset.

Procura que el teu codi sigui clar i organitzat.

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [51]:
import pandas as pd

# **Nivell 1 - EDA estructurat i neteja bàsica**

Tenim un dataset d'empleats obtingut a partir d'una enquesta interna. Abans de poder extreure conclusions, cal assegurar-nos que les dades són correctes, consistents i analitzables.

# **Exercici 1: Exploració inicial del dataset**

🎯 **Objectiu:** entendre l’estructura general del dataset i detectar possibles problemes abans de començar a netejar o transformar dades.

En aquest exercici has de realitzar una exploració inicial del DataFrame per respondre, com a mínim, a les següents preguntes:
*   Quantes files i columnes té el dataset?
*   Quin tipus de dades conté cada columna?
*   Hi ha files duplicades?
*   Les dades semblen coherents a primera vista?
*   Detectes possibles problemes o inconsistències evidents?

Per fer-ho, hauràs de:
*   Analitzar les dimensions del dataset
*   Mostrar una mostra representativa de files
*   Revisar els tipus de variables
*   Detectar files duplicades
*   Les dades semblen coherents a primera vista?
*   Identificar i descriure possibles problemes inicials (sense solucionar-los encara)

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Obrir el fitxer i carregar dades en un dataframe.
2. Obtenir les dimensions del dataframe.
3. Mostrar 10 files del dataframe.
4. Mostrar el tipus de dades de cada columna.
5. Detectar files duplicades
6. Detectar problemes amb les dades.

## 🧩 **Descomponent el problema: naixement de les funcions**

In [61]:


url = "https://github.com/roser740/Data-Analytics/raw/main/TASQUES%20S8/sprint8_complex.xlsx"
df = pd.read_excel(url, header=3)




df.info()
for col in df.columns:
  print(col)

df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1007 non-null   int64
 1   Nom                         1006 non-null   object
 2   Cognoms                     1006 non-null   object
 3   DNI                         1006 non-null   object
 4   País d'origen               1006 non-null   object
 5   Ciutat                      1006 non-null   object
 6   Dia de Naixement            1006 non-null   float64
 7   Mes de Naixement            1006 non-null   float64
 8   Any de Naixement            1006 non-null   float64
 9   Gènere                      966 non-null    object
 10  Salari mensual              1006 non-null   object
 11  Fills                       419 non-null    object
 12  No Fills                    585 non-null    object
 13  Grup Professional           1005 non-null   object
 14  CÃ rrec                     1005 non-null   object
 15  Nombre_fills                709 non-null    float64
 16  Te_cotxe                    658 non-null    object
 17  Km_anuals                   315 non-null    float64
 18  Consum_mitja_L_100km        261 non-null    float64
 19  Temperatura_mitjana_ciutat  936 non-null    float64
dtypes: float64(7), int64(1), object(12)
memory usage: 157.5+ KB
Unnamed: 0
Nom
Cognoms
DNI
País d'origen
Ciutat
Dia de Naixement
Mes de Naixement
Any de Naixement
Gènere
Salari mensual
Fills
No Fills
Grup Professional
CÃ rrec
Nombre_fills
Te_cotxe
Km_anuals
Consum_mitja_L_100km
Temperatura_mitjana_ciutat

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
5,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 â‚¬",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
6,6,David,GÃ³mez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 â‚¬",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
7,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000.0,5.9,15.4
8,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 â‚¬",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
9,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1

# **Exercici 2: Validacions bàsiques de les dades i decisions d'eliminació**

🎯 **Objectiu:** assegurar que les dades compleixen unes condicions mínimes de qualitat i determinar quines files poden continuar sent analitzades i quines s'han de descartar.
En aquest exercici hauràs de validar aspectes clau del dataset que són crítics en qualsevol context real d'anàlisi de dades, prenent decisions justificades sobre la validesa o eliminació de registres.

Aspectes a validar:

» Existeixen identificadors únics (DNI) per a cada persona?

» Què faràs amb les files duplicades o registres repetits?

» Hi ha valors obligatoris que falten o informació incoherent?

» Detectes formats incorrectes, errors de codificació o valors impossibles?

Concretament, hauràs de:

» Corregir possibles problemes de codificació i accentuació en els noms de les columnes i en els valors de text, si escau.

» Detectar i eliminar files duplicades exactes, indicant quants registres s'han eliminat.

» Comprovar la unicitat del DNI. En cas de detectar DNIs duplicats, hauràs d'analitzar la coherència de la informació associada i descartar o anul·lar els registres que no siguin fiables, justificant clarament la decisió presa.

» Identificar els camps clau que no haurien de contenir valors nuls, detectar registres amb informació insuficient i eliminar únicament aquelles files completament buides o amb informació irrecuperable o no substituïble, explicant per què no és possible ni raonable imputar-les.

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Corregir problemes de codificació i accentuació.
2. Eliminar files duplicades exactes.
3. Detectar DNIs duplicats i descartar els erronis.
4. Detectar camps clau amb valors nuls.
5. Detectar registres amb informació insuficient.

## 🧩 **Descomponent el problema: naixement de les funcions**

## **Correcció de problemes de codificació i accentuació**

El problema més comú amb els accents i la codificació (mojibake) és que el text originalment en UTF-8 es llegeix incorrectament com si fos en Latin-1 (ISO-8859-1). Per solucionar-ho, cal "desfer" la lectura incorrecta (codificant de nou a Latin-1) i després "corregir" la lectura (descodificant a UTF-8).

Aquest problema afecta tant els noms de les columnes com els valors de text dins de les columnes. Corregeixo els noms de les columnes i, posteriorment, aplico la mateixa correcció als valors de text de totes les columnes amb tipus dades 'object'.

In [56]:
def correccions (df):
  # Helper function to apply the encoding fix with error handling
  def fix_encoding_with_fallback(text):
      if isinstance(text, str):
          try:
              # Attempt to fix mojibake (UTF-8 misinterpreted as Latin-1)
              return text.encode('latin-1').decode('utf-8')
          except (UnicodeEncodeError, UnicodeDecodeError):
              # If an error occurs (e.g., the string was already correctly decoded),
              # return the original text without changes.
              return text
      return text # Return non-string types (like int, float, NaN) as is, without attempting encode/decode

  # 1. Corregir problemes de codificació i accentuació en els noms de les columnes
  df.columns = [fix_encoding_with_fallback(col) for col in df.columns]
  print("Noms de columnes corregits:")
  display(df.columns)

  # 2. Corregir problemes de codificació i accentuació en els valors de text de les columnes (general)
  # Only iterate through columns that are of 'object' dtype (usually strings) and not 'Salari mensual'
  for col in df.select_dtypes(include=['object']).columns:
      if col != 'Salari mensual': # Exclude 'Salari mensual' for specific handling later
          # Apply the helper function to each value in the column
          df[col] = df[col].apply(fix_encoding_with_fallback)

  # 3. Specific cleaning for 'Salari mensual'
  if 'Salari mensual' in df.columns:
      print("\nNetejant la columna 'Salari mensual'...")
      # Ensure it's string type first for string operations
      df['Salari mensual'] = df['Salari mensual'].astype(str)

      # Replace the incorrectly encoded euro symbol pattern (â€) with the correct one (€)
      # Based on kernel state, it's 'â' (U+00E2) followed by '€' (U+20AC)
      df['Salari mensual'] = df['Salari mensual'].str.replace('â€', '€', regex=False)
      # Standardise 'euros' text to the '€' symbol before removal
      df['Salari mensual'] = df['Salari mensual'].str.replace('euros', '€', regex=False)

      # Now, prepare for numerical conversion: remove '€', remove thousands separator ('.'), replace decimal comma (',') with dot ('.')
      df['Salari mensual'] = df['Salari mensual'].str.replace('€', '', regex=False)
      df['Salari mensual'] = df['Salari mensual'].str.replace('.', '', regex=False) # Remove thousands separator
      df['Salari mensual'] = df['Salari mensual'].str.replace(',', '.', regex=False) # Replace decimal comma

      # Convert to numeric, coercing errors to NaN
      df['Salari mensual'] = pd.to_numeric(df['Salari mensual'], errors='coerce')
      print("Columna 'Salari mensual' netejada i convertida a numèric.")
      display(df[['Salari mensual']].head())
  else:
      print("\nLa columna 'Salari mensual' no es va trobar.")

  print("\nValors de text corregits en les columnes 'object' (excepte 'Salari mensual') i un resum del DataFrame actualitzat:")
  df.info()
  display(df.head(10))

In [57]:
def main_validacio(df):
  correccions(df)

In [58]:
main_validacio(df)

Noms de columnes corregits:

Index(['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', 'País d'origen', 'Ciutat',
       'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere',
       'Salari mensual', 'Fills', 'No Fills', 'Grup Professional', 'Càrrec',
       'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km',
       'Temperatura_mitjana_ciutat'],
      dtype='object')

Netejant la columna 'Salari mensual'...
Columna 'Salari mensual' netejada i convertida a numèric.

   Salari mensual
0             NaN
1             NaN
2          1358.0
3             NaN
4             NaN

Valors de text corregits en les columnes 'object' (excepte 'Salari mensual') i un resum del DataFrame actualitzat:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1007 non-null   int64
 1   Nom                         1006 non-null   object
 2   Cognoms                     1006 non-null   object
 3   DNI                         1006 non-null   object
 4   País d'origen               1006 non-null   object
 5   Ciutat                      1006 non-null   object
 6   Dia de Naixement            1006 non-null   float64
 7   Mes de Naixement            1006 non-null   float64
 8   Any de Naixement            1006 non-null   float64
 9   Gènere                      966 non-null    object
 10  Salari mensual              127 non-null    float64
 11  Fills                       419 non-null    object
 12  No Fills                    585 non-null    object
 13  Grup Professional           1005 non-null   object
 14  Càrrec                      1005 non-null   object
 15  Nombre_fills                709 non-null    float64
 16  Te_cotxe                    658 non-null    object
 17  Km_anuals                   315 non-null    float64
 18  Consum_mitja_L_100km        261 non-null    float64
 19  Temperatura_mitjana_ciutat  936 non-null    float64
dtypes: float64(8), int64(1), object(11)
memory usage: 157.5+ KB

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,NaN,True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,NaN,NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358.0,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,NaN,True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,NaN,NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
5,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,NaN,NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
6,6,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,NaN,NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
7,7,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,NaN,True,NaN,Grup C,Responsable de vendes,4.0,True,20000.0,5.9,15.4
8,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,NaN,NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
9,9,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,NaN,True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1